---
output: html
---

# Career Goals and Benefit of Program
Since early in my medical career, I have striven to know not just what to do for patients, but why it is we use a given therapy.
What is the evidence base to support its use, and what evidentiary limiations should I keep in mind when picking a therapy?
Knowing how we came to adopt a therapeutic intervention also allows us to know the limits of our certiude on its benefits, as well as what we can do when looking for better options in the future.

Within pulmonology, our understanding of many autoinflammatory diseases has advanced over the past few decades, but our evidence base for their treatments remains woefully inadequate. 
As a pulmonary-critical care fellow and aspiring physician-scientist, my career goals are to become an academic clinician-researcher who can continue to flesh out our understanding of the sequelae of chronic pulmonary immune dysregulation, such as connective-tissue-disease-related pulmonary hypertension and autoimmune interstitial lung diseases.
I also hope to eventually work as a site principal investigator for clinical trials on these conditions, as well as to eventually run my own single- or multi-center trials on therapeutics for chronic autoinflammatory pulmonology conditions.

In my research experience to date, one of the largest roadblocks I have experieced (even with small, relatively straightforward projects) has been delays relating to statistical analyses.
Statisticians are busy, in-demand professionals, and recruiting them for small or exploratory projects can often be overshadowed by their commitments to larger or more complex undertakings.
With the training provided by the NIH-Duke CRTP, I hope to gain a foundation in statistical methods.
With this, I hope to be able to create basic plans for exploratory analyses -- especially for clinical or retrospective hypothesis-generating projects.
The CRTP would provide pragmatic experience in statistic programming with relevant languages (such as R and python).
And for projects necessitating statistical methodologies more complex than my foudnational training allows, I believe the CRTP would given me sufficient understanding to formulate research and statistical questions to better communicate, plan, and collaborate with PhD statisticians.
Finally, I believe the coursework in the CRTP focusig on trial design and analysis would prepare me to be a not only a better clinician-researcher, but also a better appraiser of clinical and translational studies in my field. 


# Research Interests 

First as a medical student, and then continued throughout both residency and fellowship, I have had a long-standing interest in the sequelae of both acute and chronic immune dysregulation within the lungs.
, such as pulmonary hypertension and autoimmune interstitial lung disease.

With my personal interest in computers and programming, I hope to utlize the ever-expanding set of tools to analyze big datasets


Most of my research on pulmonary hypertension has been epidemiological, such as attempting to quantify the global burden of the disease.
I hope to delve further into this field, and obtaining formal training in statistical methods through the NIH-Duke Masters program would be immeasurably helpful in achieving this goal.
